version: "3.9"
services:
  web:
    build:
      context: ./
    image: zhlhuang/hcms-31:3.1.0  # 根据自己项目名称定义镜像名和版本
    container_name: hcms-31-web # 容器名称根据自己项目名称定义
    volumes:
      - ./public:/opt/www/public/
    #    ports:
    #      - "9501:9501" # 默认不做映射，根据具体业务情况做映射
    links:
      - redis
    environment:
      - DB_DRIVER=mysql
      - DB_HOST=172.18.0.1 #根据宿主网卡确定ip
      - DB_PORT=3306
      - DB_DATABASE=hcms-dev
      - DB_USERNAME=root
      - DB_PASSWORD=
      - DB_CHARSET=utf8mb4
      - DB_COLLATION=utf8mb4_unicode_ci
      - DB_PREFIX=hc_
      - JWT_SECRET=hcms-auth
      - REDIS_HOST=redis
    depends_on:
      - redis
  redis:
    image: redis
    container_name: hcms-31-redis # 容器名称根据自己项目名称定义